/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package br.com.login.view;

/**
 *
 * @author Jennifer
 */
public class TelaInicialView extends javax.swing.JFrame {

    /**
     * Creates new form TelaInicialView
     */
    public TelaInicialView() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButtonCalculadora = new javax.swing.JButton();
        jButtonIMC = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButtonCalculadora.setBackground(new java.awt.Color(204, 204, 204));
        jButtonCalculadora.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonCalculadora.setForeground(new java.awt.Color(0, 153, 255));
        jButtonCalculadora.setText("Calculadora comum");
        jButtonCalculadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonCalculadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonCalculadoraActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonCalculadora, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 190, 250, 50));

        jButtonIMC.setBackground(new java.awt.Color(204, 204, 204));
        jButtonIMC.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButtonIMC.setForeground(new java.awt.Color(0, 153, 255));
        jButtonIMC.setText("Calculadora de IMC ");
        jButtonIMC.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButtonIMC.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonIMCActionPerformed(evt);
            }
        });
        getContentPane().add(jButtonIMC, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 250, 50));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Bem-vindo!");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 40, 210, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Qual calculadora você deseja utilizar?");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, -1, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/Imagem do WhatsApp de 2023-06-17 à(s) 15.07.06.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, -40, 400, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonIMCActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonIMCActionPerformed
        // TODO add your handling code here:
          CalculadoraImcView CalculadoraImc = new CalculadoraImcView();
       CalculadoraImc.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButtonIMCActionPerformed

    private void jButtonCalculadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonCalculadoraActionPerformed
        // TODO add your handling code here:
         CalculadoraView Calculadora = new CalculadoraView();
       Calculadora.setVisible(true);
       this.setVisible(false);
    }//GEN-LAST:event_jButtonCalculadoraActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaInicialView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaInicialView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonCalculadora;
    private javax.swing.JButton jButtonIMC;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    // End of variables declaration//GEN-END:variables
}
